### ISSUE TITLE
Link to Fraunhofer IAIS Artifactory doesn't immediately take to IDS-related material

### ISSUE THREAD

**Issue by clange** [International-Data-Spaces-Association/IDS-G#2]
The link from https://github.com/International-Data-Spaces-Association/IDS-G/blob/master/repositories/README.md to the Fraunhofer IAIS Artifactory doesn't immediately take the visitor to IDS-related material. It takes you to the entry page of an Artifactory containing lots of stuff. Only with some guesswork, the uninitiated visitor can imagine that `eis-ids-public` might be related to IDS.

**Comment by jlangkau** [comment]
OK! But I found it here: https://industrialdataspace.jiveon.com/docs/DOC-2611.
Please provide me witch a better link.

**Comment by ssteinbuss** [comment]
Would this work as a better link?
https://maven.iais.fraunhofer.de/ui/repos/tree/General/eis-ids-public

**Comment by sebbader** [comment]
This link brings everyone directly to the index: https://maven.iais.fraunhofer.de/artifactory/eis-ids-public/de/fraunhofer/iais/eis/ids (no UI, though. The Web UI of our JFrog has strange links, always leading to 404s if followed from outside the main UI)
