### ISSUE TITLE
IDS-G: Glossary

### ISSUE THREAD

**Issue by mohuber** [International-Data-Spaces-Association/IDS-G#22]
Hi @ssteinbuss 
there is a slight deviation between IDS-G-Pre and IDS-G concerning the glossary file.
The following file should be moved into the "Glossary" folder and the folder with old naming ("glossary") removed: https://github.com/International-Data-Spaces-Association/IDS-G/tree/main/glossary/README.md

**Comment by ssteinbuss** [comment]
Hi @mohuber ,
thanks for raising this issue. As the Q3/2021 release is not far away, we will solve this with the next release.
