### ISSUE TITLE
Missing DAPS token

### ISSUE THREAD

**Issue by HeinrichPet** [International-Data-Spaces-Association/IDS-G#4]
I miss the DAPS/security token in this example: [https://github.com/International-Data-Spaces-Association/IDS-G/blob/draft/core/InformationModel/Message/requests/DescriptionRequestMessage_POST.md ](url)

The request should look like this (same for response):
Content-Disposition: form-data; name="header"
{
  "@context" : "https://w3id.org/idsa/contexts/context.jsonld",
  "@type" : "ids:DescriptionRequestMessage",
  "modelVersion" : "3.1.0",
  "issued" : "2020-05-21T13:32:33.073+02:00",
  "issuerConnector" : "http://example.org#connector",
  "@id" : "https://w3id.org/idsa/autogen/selfDescriptionRequest/b0731661-7df1-43e5-bb75-50f0709f31c9"  
  "securityToken" : {
    "@type" : "ids:DynamicAttributeToken",
    "tokenFormat" : "https://w3id.org/idsa/code/tokenformat/JWT",
    "tokenValue" : "eyJhbGciOiJSUzI1NiIsInR5cCI..."
   }
}

**Comment by jlangkau** [comment]
done
