### ISSUE TITLE
Proposal for the documentation

### ISSUE THREAD

**Issue by vbasem** [International-Data-Spaces-Association/IDS-G#5]
Looking at the entire documentation, I believe setting up a docs page like what kubernetes offers [https://kubernetes.io/docs](https://kubernetes.io/docs) would help the community.

What do you think?

<sub> Basem Vaseghi <basem.vaseghi@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by sebbader** [comment]
Hi Basem!

Great idea, we already have a small piece of it: https://international-data-spaces-association.github.io/InformationModel/docs/index.html# is created from the IDS Information Model (https://github.com/International-Data-Spaces-Association/InformationModel/tree/develop/docs)

The layout could of course look better... But I like the idea to maintain the docs page also from open github repositories.

**Comment by ssteinbuss** [comment]
Hi, 
this is definitely needed but might take some time. Let us keep this issue open and work on it.

**Comment by ssteinbuss** [comment]
This issue is addressed in the [idsa repository](https://github.com/International-Data-Spaces-Association/idsa). Nevertheless, IDS-G has to provide a strong reference to the documentation provided there. This is not addressed, yet.

**Comment by ssteinbuss** [comment]
This issue is solved with the docs section at the IDSA Homepage. At least as a starting point. We should continue to improve there. https://docs.internationaldataspaces.org/
