### ISSUE TITLE
CONTRIBUTING.md refers to IDS-G-pre

### ISSUE THREAD

**Issue by sebbader** [International-Data-Spaces-Association/IDS-G#50]
There are outdated references in this file which need to be fixed. Example:

https://github.com/International-Data-Spaces-Association/IDS-G/blob/develop/CONTRIBUTING.md
<img width="802" alt="image" src="https://user-images.githubusercontent.com/12392907/191712378-936dcb9f-cbae-45ad-8535-91252ff4fef0.png">

**Comment by ssteinbuss** [comment]
fixed by #51
