### ISSUE TITLE
Update Contract negotiation part in Communication Guide

### ISSUE THREAD

**Issue by ssteinbuss** [International-Data-Spaces-Association/IDS-G#61]
Please prepare a draft for the Contract negotiation

**Comment by ssteinbuss** [comment]
@Brandstaedter @juliapampus could you support @jimmarino  with this issue

**Comment by Brandstaedter** [comment]
Hi, could send this link, where to update?!

best regards

**Comment by juliapampus** [comment]
should we set up a meeting? @jimmarino @Brandstaedter

**Comment by gbrost** [comment]
Please count us in: @gbrost @milux

**Comment by jimmarino** [comment]
Completed
