### ISSUE TITLE
Extension of the Policy Classes

### ISSUE THREAD

**Issue by hosseinzadeha** [International-Data-Spaces-Association/IDS-G#91]
So far 21 Policy Classes have been introduced. The intention of having/extending Policy Classes, is to have simply atomic policy templates. One can instantiate and combine them intro a Usage Control policy.

The sample policies are split into separated json files (in ODRL and IDS namespace) and are available here: [https://github.com/International-Data-Spaces-Association/IDS-G/tree/UC-branch/UsageControl/Contract/Policies](https://github.com/International-Data-Spaces-Association/IDS-G/tree/UC-branch/UsageControl/Contract/Policies)

The policies that are specified in IDS namespace are compatible with the latest release of IDS info model. As soon as a new release is available, they will be updated too.

This issue is created to address the point that two Policy Classes are added:
22. Restrict the data usage to the location of the participant
23. Restrict the data usage to the user consent

A pull request will be created accordingly.

**Comment by hosseinzadeha** [comment]
The relevant pull request is still pending (https://github.com/International-Data-Spaces-Association/IDS-G/pull/92).

**Comment by JessicaRombs** [comment]
Relevant Pull Request Approved and Merged (#92).
